#! /bin/bash

cat log.txt
echo "---------"

echo "--Ten Second Rankings--"
echo "X STANDARD DEVIATION"
for file in "${@}"

do
./statline-10s ${file} 
done | column -t | sort -n -k 3

echo "----------"

echo "Y STANDARD DEVIATION"
for file in "${@}"

do
./statline-10s ${file} 
done | column -t | sort -n -k 5

echo "----------"

echo "TOTAL STANDARD DEVIATION"

for file in "${@}"

do
./statline-10s ${file} 
done | column -t | sort -n -k 6

echo "----------"

cat Winner.txt

