#! /bin/bash

for file in "${@}"

do

starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")
xavg=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $2}' | tail -n +2 | ./avg.py)

xdis=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $2}' | gawk -v x="${xavg}" '{diff = x - $1}; {xsq = diff**2}; { print xsq }')

yavg=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000,NF > 1 {print $3}' | tail -n +2 | ./avg.py) 

ydis=$(cat ${file} | gawk -v y="${starttime}" '$1 < y + 10000, NF > 1 {print $3}' | gawk -v y="${yavg}" '{diff = y - $1}; {ysq = diff**2}; { print ysq }')

xsepy=$(paste <(echo "${xdis}") <(echo "${ydis}") -d ' ')

echo "${xsepy}" | tail -n +2 | gawk '{sum = $1 + $2}; {totdis = sum**0.5}; { print totdis }'

done
