#! /bin/bash

for file in "${@}"

do

starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")

xstdev=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $2}' | tail -n +2 | ./stddev.py | ./square.py)

ystdev=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000, NF > 1 {print $3}' | tail -n +2 | ./stddev.py | ./square.py)

totstd=$(echo "${xstdev} + ${ystdev}" | bc | ./sqrt.py) 

echo " ${file} ${totstd}"

done | column -t


