#! /bin/bash

for file in "${@}"

do
starttime=$(cat ${file} | head -n 2 | tail -n 1 | cut -f 1 -d " ")

yavg=$(cat ${file} | gawk -v x="${starttime}" '$1 < x + 10000,NF > 1 {print $3}' | tail -n +2 | ./avg.py) 

ydis=$(cat ${file} | gawk -v y="${starttime}" '$1 < y + 10000, NF > 1 {print $3}' | gawk -v y="${yavg}" '{diff = y - $1}; {ysq = diff**2}; { print ysq }')

done

echo "${ydis}"

